/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReceiverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "messageReceived"
      | "messageService"
      | "onReceiveMessage"
      | "remoteSender"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "messageReceived",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageService",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onReceiveMessage",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "remoteSender",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "messageReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onReceiveMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remoteSender",
    data: BytesLike
  ): Result;
}

export interface Receiver extends BaseContract {
  connect(runner?: ContractRunner | null): Receiver;
  waitForDeployment(): Promise<this>;

  interface: ReceiverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  messageReceived: TypedContractMethod<[], [string], "view">;

  messageService: TypedContractMethod<[], [string], "view">;

  onReceiveMessage: TypedContractMethod<
    [messageToL: string],
    [void],
    "nonpayable"
  >;

  remoteSender: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "messageReceived"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "messageService"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onReceiveMessage"
  ): TypedContractMethod<[messageToL: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remoteSender"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
